spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  boot:
    admin:
      client:
        url: http://admin-service:8080
        #url: http://admin-server:8080
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-service
          #brokers: kafka-server
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-service
      #host: jaeger-server
      port: 6831
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
