spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  boot:
    admin:
      client:
        url: http://admin-server:8080
opentracing:
  jaeger:
    udp-sender:
      host: jaeger-server
      port: 6831
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
