server:
  port: 10000
spring:
  cloud:
    stream:
#      source: paymentsChannel
      #      function:
      #        bindings:
      #          paymentsChannel-in-0: paymentsChannel
      bindings:
        paymentsChannel-out-0:
          destination: Payments
payments-broker:
  paymentsBrokerServiceName: payments-broker
  paymentsResource: /payments