spring:
  cloud:
    stream:
      function:
        bindings:
          paymentsChannel-in-0: paymentsChannel
      bindings:
        paymentsChannel:
          destination: Payments
          group: shop
