server:
  port: 10001
spring:
  cloud:
    stream:
#      function:
#        bindings:
#          paymentsChannel-in-0: paymentsChannel
      bindings:
        paymentsChannel-in-0:
          destination: Payments
          content-type: application/json
          group: payments-updates
          consumer:
            concurrency: 10
