server:
  port: 10001
spring:
  cloud:
    function:
      definition: paymentsChannel
    stream:
      function:
        bindings:
          paymentsChannel-in-0: paymentsChannel
      bindings:
        paymentsChannel:
          destination: Payments
          content-type: application/json
          group: payments
