server:
  port: 10001
spring:
  cloud:
    function:
      definition: paymentsChannel
    stream:
      bindings:
        paymentsChannel-in-0:
          destination: Payments
          group: payments
