spring:
  application:
    name: shop-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 003-C`ommunication
  profiles:
    active: development