POST localhost:8080/payments
Accept: application/json
Content-Type: application/json

{
  "value": "100 PLN",
  "settings": {
    "cardNumber": "123456789",
    "cvv": 255
  }
}

###

GET localhost:8080/payments/ede66483-c2a0-4a1c-81d0-92cfaad11d21
Accept: application/json
Content-Type: application/json