spring:
  application:
    name: payments-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 004-Monitoring-and-tracing
  profiles:
    active: development