spring:
  application:
    name: payments-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 002-Base-elements # default
      # uri: http://localhost:8888 old way
#  profiles:
#    active: development