spring:
  application:
    name: payments-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 007-resilience4j
  profiles:
    active: development