apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: admin
  template:
    metadata:
      labels:
        app-name: admin
    spec:
      containers:
        - name: admin
          image: landrzejewski/admin-server-t
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080

