apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: jaeger
  template:
    metadata:
      labels:
        app-name: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          ports:
            - containerPort: 16686
