apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: kafka
  template:
    metadata:
      labels:
        app-name: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config-map
