apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app-name: payments-service
  template:
    metadata:
      labels:
        app-name: payments-service
    spec:
      containers:
        - name: payments-service
          image: landrzejewski/payments-service-t
          envFrom:
            - configMapRef:
                name: common-config-map
          ports:
            - containerPort: 9000

