apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: redis
  template:
    metadata:
      labels:
        app-name: redis
    spec:
      containers:
        - name: redis
          image: redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379

