apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app-name: zookeeper
  ports:
    - name: clinet
      port: 2181
    - name: follower
      port: 2888
    - name: leader
      port: 3888
