spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 002-Base-elements
  profiles:
    active: development