spring:
  application:
    name: payments-broker
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: 003-Communication
  profiles:
    active: development